// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package company_updates

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CompanyUpdate struct {
	ID                int32          `json:"id"`
	CompanyUpdateUid  uuid.UUID      `json:"company_update_uid"`
	Title             string         `json:"title"`
	Description       string         `json:"description"`
	UpdateCategory    string         `json:"update_category"`
	UpdateType        string         `json:"update_type"`
	SourceType        string         `json:"source_type"`
	SourceUrl         string         `json:"source_url"`
	PostedAt          time.Time      `json:"posted_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	ActionPoint       sql.NullString `json:"action_point"`
	TrackedCompanyUid uuid.UUID      `json:"tracked_company_uid"`
	IsSaved           sql.NullBool   `json:"is_saved"`
}

type Customer struct {
	ID                      int32          `json:"id"`
	CustomerUid             uuid.UUID      `json:"customer_uid"`
	Email                   string         `json:"email"`
	Domain                  sql.NullString `json:"domain"`
	SubscriptionUid         uuid.NullUUID  `json:"subscription_uid"`
	IsTrialExpired          sql.NullBool   `json:"is_trial_expired"`
	IsSubscriptionActive    sql.NullBool   `json:"is_subscription_active"`
	IsVerified              sql.NullBool   `json:"is_verified"`
	VerificationToken       sql.NullString `json:"verification_token"`
	VerificationTokenSentAt sql.NullTime   `json:"verification_token_sent_at"`
	OnboardingCompletion    sql.NullBool   `json:"onboarding_completion"`
	CreatedAt               sql.NullTime   `json:"created_at"`
	CustomerContext         sql.NullString `json:"customer_context"`
	OwnerID                 sql.NullInt32  `json:"owner_id"`
}

type Department struct {
	ID            int32     `json:"id"`
	DepartmentUid uuid.UUID `json:"department_uid"`
	Name          string    `json:"name"`
}

type EmailRecipient struct {
	ID                int32     `json:"id"`
	EmailRecipientUid uuid.UUID `json:"email_recipient_uid"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	DepartmentUid     uuid.UUID `json:"department_uid"`
	CustomerUid       uuid.UUID `json:"customer_uid"`
	CreatedAt         time.Time `json:"created_at"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type TrackedCompany struct {
	ID                int32          `json:"id"`
	TrackedCompanyUid uuid.UUID      `json:"tracked_company_uid"`
	Name              string         `json:"name"`
	Domain            string         `json:"domain"`
	Type              string         `json:"type"`
	Interests         []string       `json:"interests"`
	CustomerUid       uuid.UUID      `json:"customer_uid"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	LinkedinUsername  sql.NullString `json:"linkedin_username"`
	ChangelogsUrl     sql.NullString `json:"changelogs_url"`
	// Flag indicating whether the company tracking is active
	Isactive bool `json:"isactive"`
}

type User struct {
	ID            int32          `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Name          sql.NullString `json:"name"`
	Email         string         `json:"email"`
	IsVerified    sql.NullBool   `json:"is_verified"`
	CustomerUid   uuid.NullUUID  `json:"customer_uid"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	Role          sql.NullString `json:"role"`
	ClerkID       sql.NullString `json:"clerk_id"`
	DepartmentUid uuid.NullUUID  `json:"department_uid"`
}
