// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CompanyUpdate struct {
	CompanyUpdateUID  string  `json:"CompanyUpdateUID"`
	Title             string  `json:"Title"`
	Description       string  `json:"Description"`
	UpdateCategory    string  `json:"UpdateCategory"`
	UpdateType        string  `json:"UpdateType"`
	SourceType        string  `json:"SourceType"`
	SourceURL         string  `json:"SourceURL"`
	PostedAt          string  `json:"PostedAt"`
	CreatedAt         string  `json:"CreatedAt"`
	ActionPoint       *string `json:"ActionPoint,omitempty"`
	TrackedCompanyUID string  `json:"TrackedCompanyUID"`
	Domain            string  `json:"Domain"`
}

type CreateEmailRecipientInput struct {
	Name          string `json:"name"`
	Email         string `json:"email"`
	DepartmentUID string `json:"departmentUID"`
}

type CreateTrackedCompanyInput struct {
	Name      string   `json:"name"`
	Domain    string   `json:"domain"`
	Type      string   `json:"type"`
	Interests []string `json:"interests"`
}

type Customer struct {
	ID                   *int    `json:"Id,omitempty"`
	Email                *string `json:"Email,omitempty"`
	Domain               *string `json:"Domain,omitempty"`
	CustomerUID          *string `json:"CustomerUID,omitempty"`
	IsVerified           *bool   `json:"IsVerified,omitempty"`
	OnboardingCompletion *bool   `json:"OnboardingCompletion,omitempty"`
}

type DeleteEmailRecipientInput struct {
	EmailRecipientUID string `json:"emailRecipientUID"`
}

type DeleteEmailRecipientResponse struct {
	Success bool `json:"success"`
}

type DeleteTrackedCompanyInput struct {
	TrackedCompanyUID string `json:"trackedCompanyUID"`
}

type Department struct {
	DepartmentUID string `json:"departmentUID"`
	Name          string `json:"name"`
}

type EmailRecipient struct {
	ID                int    `json:"id"`
	EmailRecipientUID string `json:"emailRecipientUID"`
	Name              string `json:"name"`
	Email             string `json:"email"`
	IsActive          bool   `json:"isActive"`
	DepartmentUID     string `json:"departmentUID"`
	CustomerUID       string `json:"customerUID"`
	CreatedAt         string `json:"createdAt"`
}

type InviteData struct {
	DepartmentUID string `json:"departmentUID"`
	IsValid       bool   `json:"isValid"`
	CustomerUID   string `json:"customerUID"`
	ExpiresAt     string `json:"expiresAt"`
	CreatedAt     string `json:"createdAt"`
}

type InviteEmailRecipientInput struct {
	DepartmentUID string `json:"departmentUID"`
}

type InviteEmailRecipientResponse struct {
	InviteToken string `json:"inviteToken"`
}

type Mutation struct {
}

type Query struct {
}

type SigninInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SigninReponse struct {
	Token string `json:"token"`
}

type SignupInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignupResponse struct {
	User        *User   `json:"user,omitempty"`
	UserID      string  `json:"userId"`
	ClerkID     *string `json:"clerkId,omitempty"`
	CustomerUID *string `json:"customerUID,omitempty"`
}

type TrackedCompany struct {
	TrackedCompanyUID string   `json:"TrackedCompanyUID"`
	Name              string   `json:"Name"`
	Domain            string   `json:"Domain"`
	Type              string   `json:"Type"`
	Interests         []string `json:"Interests"`
	CustomerUID       string   `json:"CustomerUID"`
	CreatedAt         string   `json:"CreatedAt"`
	IsActive          bool     `json:"IsActive"`
}

type UpdateCustomerAndUserInput struct {
	Name   string `json:"name"`
	Domain string `json:"domain"`
	Role   string `json:"role"`
}

type UpdateEmailRecipientInput struct {
	EmailRecipientUID string  `json:"emailRecipientUID"`
	Name              *string `json:"name,omitempty"`
	Email             *string `json:"email,omitempty"`
	DepartmentUID     *string `json:"departmentUID,omitempty"`
	IsActive          *bool   `json:"isActive,omitempty"`
}

type UpdateTrackedCompanyInput struct {
	TrackedCompanyUID string   `json:"trackedCompanyUID"`
	Type              *string  `json:"type,omitempty"`
	Interests         []string `json:"interests,omitempty"`
	IsActive          *bool    `json:"isActive,omitempty"`
}

type User struct {
	ID          string  `json:"id"`
	UserUID     string  `json:"userUID"`
	Name        *string `json:"name,omitempty"`
	Email       string  `json:"email"`
	Role        *string `json:"role,omitempty"`
	IsVerified  *bool   `json:"isVerified,omitempty"`
	CustomerUID *string `json:"customerUID,omitempty"`
	ClerkID     *string `json:"clerkId,omitempty"`
}

type ValidateInviteInput struct {
	Token string `json:"token"`
}

type VerifyCustomerInput struct {
	Token string `json:"token"`
}

type VerifyCustomerResponse struct {
	Success              bool   `json:"success"`
	Token                string `json:"token"`
	OnboardingCompletion bool   `json:"OnboardingCompletion"`
}
