package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"flint/graph/model"
	"fmt"
)

// GetCompanyUpdates is the resolver for the getCompanyUpdates field.
func (r *queryResolver) GetCompanyUpdates(ctx context.Context) ([]*model.CompanyUpdate, error) {
	company_updates, err := r.companyUpdateService.GetAllCompanyUpdates(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get company updates: %w", err)
	}
	return company_updates, nil
}
