package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"flint/graph/model"
	"fmt"
)

// InviteEmailRecipient is the resolver for the inviteEmailRecipient field.
func (r *mutationResolver) InviteEmailRecipient(ctx context.Context, input model.InviteEmailRecipientInput) (*model.InviteEmailRecipientResponse, error) {
	return r.emailRecipientsService.InviteEmailRecipient(ctx, input)
}

// CreateEmailRecipient is the resolver for the createEmailRecipient field.
func (r *mutationResolver) CreateEmailRecipient(ctx context.Context, input model.CreateEmailRecipientInput) (*model.EmailRecipient, error) {
	return r.emailRecipientsService.CreateEmailRecipient(ctx, input)
}

// UpdateEmailRecipient is the resolver for the updateEmailRecipient field.
func (r *mutationResolver) UpdateEmailRecipient(ctx context.Context, input model.UpdateEmailRecipientInput) (*model.EmailRecipient, error) {
	return r.emailRecipientsService.UpdateEmailRecipientByInput(ctx, input)
}

// DeleteEmailRecipeint is the resolver for the deleteEmailRecipeint field.
func (r *mutationResolver) DeleteEmailRecipeint(ctx context.Context, input *model.DeleteEmailRecipientInput) (*model.DeleteEmailRecipientResponse, error) {
	return r.emailRecipientsService.DeleteEmailRecipientByUID(ctx, *input)
}

// ValidateInvite is the resolver for the validateInvite field.
func (r *queryResolver) ValidateInvite(ctx context.Context, input model.ValidateInviteInput) (*model.InviteData, error) {
	return r.emailRecipientsService.ValidateInvite(ctx, input)
}

// GetAllEmailRecipients is the resolver for the getAllEmailRecipients field.
func (r *queryResolver) GetAllEmailRecipients(ctx context.Context) ([]*model.EmailRecipient, error) {
	emailRecipients, err := r.emailRecipientsService.GetEmailRecipients(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get all email recipients: %w", err)
	}
	return emailRecipients, nil
}
