package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"flint/graph/model"
)

// GetAccountUsers is the resolver for the getAccountUsers field.
func (r *queryResolver) GetAccountUsers(ctx context.Context) ([]*model.User, error) {
	// panic(fmt.Errorf("not implemented: GetAccountUsers - getAccountUsers"))
	res, err := r.userService.GetAccountUsers(ctx)
	if err != nil {
		return res, err
	}
	return res, nil
}
